FROM python:3.12-alpine AS builder

RUN apk add --no-cache \
    curl \
    build-base

RUN python -m pip install --upgrade pip && \
    pip install uv

WORKDIR /src
COPY ./pyproject.toml ./uv.lock* ./

RUN uv venv && \
    uv sync --no-cache --only-group cron


FROM python:3.12-alpine

LABEL authors="aleksander.marszalki"
LABEL name="crony"

WORKDIR /src

RUN apk add --no-cache \
    procps \
    curl \
    tzdata \
    bash \
    dcron

COPY --from=builder /src/.venv ./.venv

COPY ../src .

ENV PATH="/src/.venv/bin:/usr/local/bin:$PATH"

RUN mkdir /log

COPY docker/crontab /etc/crontabs/root
RUN sed -i 's/\r$//' /etc/crontabs/root && \
    chmod 0644 /etc/crontabs/root

RUN mkdir -p /log && \
    touch /log/snapshooter.log && \
    chmod 666 /log/snapshooter.log

COPY docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

COPY docker/run-cron-job.sh /run-cron-job.sh
RUN chmod +x /run-cron-job.sh

ENTRYPOINT ["/entrypoint.sh"]
