FROM python:3.12.10-slim-bullseye
LABEL authors="aleksander.marszalki"
LABEL name="crony"

WORKDIR /src

RUN apt-get update && apt-get install --no-install-recommends -y \
    procps \
    build-essential \
    curl \
    software-properties-common \
    tzdata \
    cron \
    bash \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get purge -y build-essential

RUN python -m pip install --upgrade pip --break-system-packages && \
    pip install uv --break-system-packages

COPY ./pyproject.toml ./uv.lock ./
RUN uv lock --no-cache
RUN uv sync --no-cache --only-group cron

COPY ../src .

ENV PATH="/src/.venv/bin:/usr/local/bin:$PATH"

RUN mkdir /log

EXPOSE 8501/tcp

COPY docker/crontab /etc/cron.d/snapshooter-cron
RUN sed -i 's/\r$//' /etc/cron.d/snapshooter-cron
RUN chmod 0644 /etc/cron.d/snapshooter-cron

RUN mkdir -p /log && \
    touch /log/snapshooter.log && \
    chmod 666 /log/snapshooter.log

COPY docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
